# Generated by Django 3.1.4 on 2020-12-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201215_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vote_total',
            field=models.IntegerField(default=0),
        ),
    ]
